@extends('layouts.app')
@section('title',$draft ? 'Edit draft' : 'Compose draft')
@section('content')
<h1>{{ $draft ? 'Edit draft' : 'Compose draft' }}</h1>
@if(session('outboundError'))<div class="alert alert--error">{{ session('outboundError') }}</div>@endif
<form method="POST" action="{{ $draft ? route('outbound-drafts.update',$draft) : route('outbound-drafts.store') }}" class="card">@csrf @if($draft) @method('PATCH')<input type="hidden" name="version" value="{{ $draft->draft_version }}">@endif
<div class="form-field"><label>Sender inbox</label><select name="inbox_id" required>@foreach($inboxes as $inbox)<option value="{{ $inbox->id }}" @selected(old('inbox_id',$draft?->inbox_id)==$inbox->id)>{{ $inbox->full_address }}</option>@endforeach</select></div>
<div class="form-field"><label>Operation</label><select name="operation"><option value="send" @selected($operation==='send')>Send</option><option value="reply" @selected($operation==='reply')>Reply</option><option value="forward" @selected($operation==='forward')>Forward</option></select></div>
<div class="form-field"><label>To (comma-separated)</label><input name="to[]" value="{{ old('to.0',$draft?->to_recipients[0] ?? '') }}"></div><div class="form-field"><label>Subject</label><input name="subject" value="{{ old('subject',$draft?->subject) }}"></div><div class="form-field"><label>Text body</label><textarea name="text_body" rows="8">{{ old('text_body',$draft?->text_body) }}</textarea></div><div class="form-field"><label>HTML body</label><textarea name="html_body" rows="5">{{ old('html_body',$draft?->html_body) }}</textarea></div><button class="btn btn--primary">Save draft</button></form>
@if($draft)<form method="POST" action="{{ route('outbound-drafts.submit',$draft) }}" style="margin-top:1rem">@csrf<input type="hidden" name="version" value="{{ $draft->draft_version }}"><button class="btn btn--primary">Submit</button></form><form method="POST" action="{{ route('outbound-drafts.destroy',$draft) }}" style="margin-top:1rem" onsubmit="return confirm('Delete this draft?')">@csrf @method('DELETE')<input type="hidden" name="version" value="{{ $draft->draft_version }}"><button class="btn btn--danger">Delete</button></form>@endif
@endsection
